version: '3.3'

services:
  web:
    build: .
    command: >
      sh -c "gunicorn hotelApi.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      # - redis
      - migration


  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hack_v2
      POSTGRES_USER: bekbolsun
      POSTGRES_PASSWORD: 1
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  migration:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate"
    volumes:
      - .:/usr/src/app/
    depends_on:
      - db

  # celery-beat:
  #   build: .
  #   command: celery -A config beat -l INFO
  #   volumes:
  #     - .:/usr/src/app/
  #   depends_on:
  #     - web
  #     - redis

  redis:
     image: redis
     ports:
       - "6379:6379"

  # celery:
  #   build: .
  #   command: celery -A config worker -l INFO

  #   volumes:
  #     - .:/usr/src/app/
  #   depends_on:
  #     - web
  #     - redis



  nginx:
     build:
       context: .
       dockerfile: nginx/Dockerfile
     ports:
       - "80:80"
     volumes:
       - static_volume:/usr/src/app/static
       - media_volume:/usr/src/app/media
     depends_on:
       - web

volumes:
  postgres_data:
  static_volume:
  media_volume:



#version: '3'
#
#services:
#  nginx:
#    build: ./nginx
#    volumes:
#        - shared_volume:/root
#    links:
#        - django
#    ports:
#        - "80:80"
#
#  django:
#    build: .
#    volumes:
#        - .:/root
#        - shared_volume:/usr/src/app
#    expose:
#        - "8000"
#    links:
#        - postgres
#
#  postgres:
#    image: postgres:latest
#
#volumes:
#  shared_volume:
